# Generated by Django 5.2.13 on 2026-04-29 06:41

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('UMRAH', 'Umrah'), ('HAJJ', 'Hajj'), ('VISIT', 'Visit Visa'), ('FLIGHT_INTL', 'International Flight'), ('FLIGHT_DOM', 'Domestic Flight'), ('TOUR', 'Tour Package'), ('OTHER', 'Other')], default='UMRAH', max_length=20)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-departure_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('supplier_type', models.CharField(choices=[('AIRLINE', 'Airline'), ('HOTEL', 'Hotel'), ('VISA', 'Visa Provider'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='CNIC')),
                ('passport_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_issue_country', models.CharField(blank=True, default='Pakistan', max_length=60)),
                ('visa_number', models.CharField(blank=True, max_length=60)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['passport_number'], name='crm_passeng_passpor_887cd2_idx'), models.Index(fields=['cnic'], name='crm_passeng_cnic_a1dbe0_idx'), models.Index(fields=['mobile'], name='crm_passeng_mobile_93ad2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default='Member', max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.passenger')),
            ],
            options={
                'unique_together': {('group', 'passenger')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='crm.passenger'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='crm.GroupMembership', to='crm.passenger'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport Scan'), ('VISA', 'Visa Copy'), ('TICKET', 'E-Ticket'), ('CNIC', 'CNIC'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], default='PASSPORT', max_length=20)),
                ('file', models.FileField(upload_to=crm.models.passenger_doc_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.passenger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('UMRAH', 'Umrah'), ('HAJJ', 'Hajj'), ('VISIT', 'Visit Visa'), ('FLIGHT_INTL', 'International Flight'), ('FLIGHT_DOM', 'Domestic Flight'), ('TOUR', 'Tour Package'), ('OTHER', 'Other')], default='UMRAH', max_length=20)),
                ('package_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='crm.group')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='crm.passenger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('received_on', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.booking')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='crm.booking')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.supplier')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
