# Generated by Django 5.2.13 on 2026-04-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='saudi_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('OUT', 'Pakistan to KSA'), ('IN', 'KSA to Pakistan'), ('OTHER', 'Other')], default='OUT', max_length=10)),
                ('flight_no', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='crm.booking')),
            ],
            options={
                'ordering': ['direction', 'departure', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('confirm_no', models.CharField(blank=True, max_length=80)),
                ('room_type', models.CharField(blank=True, max_length=120)),
                ('meal_plan', models.CharField(choices=[('RO', 'Room Only (RO)'), ('BB', 'Bed & Breakfast (BB)'), ('HB', 'Half Board (HB)'), ('FB', 'Full Board (FB)')], default='RO', max_length=4)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='crm.booking')),
            ],
            options={
                'ordering': ['check_in', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('transport_type', models.CharField(max_length=120)),
                ('brn', models.CharField(blank=True, max_length=80)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='crm.booking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pax_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('INFANT', 'Infant')], default='ADULT', max_length=10)),
                ('bed', models.BooleanField(default=True)),
                ('visa_number', models.CharField(blank=True, max_length=80)),
                ('pnr', models.CharField(blank=True, max_length=40)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pax', to='crm.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.passenger')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('booking', 'passenger')},
            },
        ),
    ]
