# Generated by Django 5.2.13 on 2026-04-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_booking_branch_booking_group_no_booking_manual_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookinghotel',
            name='hotel_name',
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('default_meal_plan', models.CharField(choices=[('RO', 'Room Only (RO)'), ('BB', 'Bed & Breakfast (BB)'), ('HB', 'Half Board (HB)'), ('FB', 'Full Board (FB)')], default='RO', max_length=4)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='booking_stays', to='crm.hotel'),
            preserve_default=False,
        ),
    ]
