# Generated by Django 5.2.13 on 2026-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_bookinghotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='extra_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='occupants',
            field=models.PositiveSmallIntegerField(default=2, help_text='People per room'),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='room_basis',
            field=models.CharField(choices=[('SHARING', 'Sharing (with other pilgrims)'), ('PRIVATE', 'Private (own room)')], default='SHARING', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='room_notes',
            field=models.CharField(blank=True, help_text='e.g. mother+daughter, no smoking, view', max_length=200),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='rooms_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many rooms of this type'),
        ),
        migrations.AlterField(
            model_name='bookinghotel',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single (1 Bed)'), ('DOUBLE', 'Double (2 Beds)'), ('TRIPLE', 'Triple (3 Beds)'), ('QUAD', 'Quad (4 Beds)'), ('QUINT', 'Quintuple (5 Beds)'), ('FAMILY', 'Family Suite'), ('OTHER', 'Other')], default='DOUBLE', max_length=20),
        ),
    ]
