# Generated by Django 5.2.13 on 2026-04-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_bookinghotel_extra_bed_bookinghotel_occupants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text='IATA code, e.g. SV, PK, EK', max_length=10)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bookingtransport',
            name='transport_mode',
            field=models.CharField(choices=[('BUS', 'Bus (Sharing / Group)'), ('PRIVATE', 'Private Car'), ('VAN', 'Van / Coaster'), ('GMC', 'GMC / SUV'), ('TRAIN', 'Haramain Train'), ('OTHER', 'Other')], default='BUS', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingtransport',
            name='name',
            field=models.CharField(help_text='Route or service name (e.g. JED-MAK-MED-JED)', max_length=120),
        ),
        migrations.AlterField(
            model_name='bookingtransport',
            name='transport_type',
            field=models.CharField(blank=True, help_text='Optional details (e.g. AC Coaster, Toyota Hiace)', max_length=120),
        ),
        migrations.AddField(
            model_name='bookingflight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_flights', to='crm.airline'),
        ),
    ]
